// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcyEaXVAdOPd27JB1iLGrPot1z_xs6cu0',
    appId: '1:747246086812:web:0a9fdb67c112e7e85c5b59',
    messagingSenderId: '747246086812',
    projectId: 'lifelink-66e5b',
    authDomain: 'lifelink-66e5b.firebaseapp.com',
    storageBucket: 'lifelink-66e5b.firebasestorage.app',
    measurementId: 'G-PXM3WT5MHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApxDQr8_gKe2Ob2pjVvpaRI6gTold7Q5c',
    appId: '1:747246086812:android:675a0cdb01b7885e5c5b59',
    messagingSenderId: '747246086812',
    projectId: 'lifelink-66e5b',
    storageBucket: 'lifelink-66e5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV1zFJsDKj-02KgKITucRSRmIs3IqsJo4',
    appId: '1:747246086812:ios:80e8578a97b767165c5b59',
    messagingSenderId: '747246086812',
    projectId: 'lifelink-66e5b',
    storageBucket: 'lifelink-66e5b.firebasestorage.app',
    iosBundleId: 'com.example.lifelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV1zFJsDKj-02KgKITucRSRmIs3IqsJo4',
    appId: '1:747246086812:ios:80e8578a97b767165c5b59',
    messagingSenderId: '747246086812',
    projectId: 'lifelink-66e5b',
    storageBucket: 'lifelink-66e5b.firebasestorage.app',
    iosBundleId: 'com.example.lifelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcyEaXVAdOPd27JB1iLGrPot1z_xs6cu0',
    appId: '1:747246086812:web:3f8cb1904543bd735c5b59',
    messagingSenderId: '747246086812',
    projectId: 'lifelink-66e5b',
    authDomain: 'lifelink-66e5b.firebaseapp.com',
    storageBucket: 'lifelink-66e5b.firebasestorage.app',
    measurementId: 'G-7DLG8L90T0',
  );
}
